name: JobsBoostIndicator
description: JobsBoostIndicator that shows boost status of Jobs
main: org.dr_romantic.jbi.main.JobsBoostIndicator
version: 1.0.5
api-version: 1.13
authors: [DrRomantic, Anco_]
softdepend: [Jobs]
commands:
  직업부스트:
    description: Show the status of own jobs
    usage: /직업부스트
    aliases: [jb,직부]