name: JobsBoostIndicator
description: JobsBoostIndicator that shows boost status of Jobs
main: org.dr_romantic.jbi.main.JobsBoostIndicator
version: 1.0.2
api-version: 1.13
authors: [DrRomantic, Anco]
softdepend: [Jobs]
commands:
  직업부스트:
    description: Show the status of own jobs
    usage: /직업부스트
    aliases: [jb,jobsboost,직부]